apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      version: v1
      kind: Service
      name: argocd-server
    patch: |
      - op: add
        path: /spec/ports/0/appProtocol
        value: grpc
      - op: add
        path: /spec/ports/1/appProtocol
        value: grpc
